### ISSUE TITLE
address output changed breaking compatiblity

### ISSUE THREAD

**Issue by tommymcguiver** [Nekroze/ishmael#21]
Following commit broke our scripts: 

https://github.com/Nekroze/ishmael/commit/f1aefd851f97df6571d6a9e38eeec420db1eb7dd

Need a way of restricting output to restore compatibility

**Comment by Nekroze** [comment]
@tommymcguiver this change only adding more output, in what way is it not backwards compatible?

**Comment by Nekroze** [comment]
I beleive what you are seeing is a bug in dab, during a refactor the grep was broken, you can still get the same output as before using `dab apps address` which will give the unfiltered address, `dab apps start` is now just meant to display the mapped ports which is indeed broken with a fix impending.

**Comment by Nekroze** [comment]
real issue addressed in Nekroze/dab/pull/356 as I understand it. Should this not be the case please do not hesitate to reopen this issue.
